openapi: "3.0.0"
info:
  title: API1
  description: テストAPI1
  version: 0.0.1
paths:
  "/hello":
    get:
      summary: "hello"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "hello"
