openapi: "3.0.0"
info:
  title: API2
  description: テストAPI2
  version: 0.0.1
paths:
  "/helloworld":
    get:
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: "hello world"
